# This is a configuration file for using the travis-ci.org continuos integration
# and codeclimate.com systems.

language: ruby
script: bundle exec rake test
rvm:
  - 2.3.2
gemfile:
  - Gemfile
addons:
    code_climate:
        repo_token: 60b467bf610dd1c7bd82459817f479feaf9b9b33aec9c181f4b7a431a4ff7080
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c08e777889b5e121f914
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
